// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stest.proto

package stest

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2e3ff4bd061710a, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Empty)(nil), "stest.Empty")
}

func init() { proto.RegisterFile("stest.proto", fileDescriptor_c2e3ff4bd061710a) }

var fileDescriptor_c2e3ff4bd061710a = []byte{
	// 86 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x2e, 0x49, 0x2d,
	0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xd8, 0xb9, 0x58, 0x5d,
	0x73, 0x0b, 0x4a, 0x2a, 0x8d, 0x4c, 0xb9, 0x78, 0x82, 0x41, 0x22, 0xc1, 0xa9, 0x45, 0x65, 0x99,
	0xc9, 0xa9, 0x42, 0xaa, 0x5c, 0xac, 0x60, 0xbe, 0x10, 0x8f, 0x1e, 0x44, 0x1b, 0x58, 0x99, 0x14,
	0x0a, 0x4f, 0x89, 0x21, 0x89, 0x0d, 0x6c, 0x9a, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x19, 0x48,
	0xf2, 0xca, 0x5c, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StestServiceClient is the client API for StestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StestServiceClient interface {
	Stest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type stestServiceClient struct {
	cc *grpc.ClientConn
}

func NewStestServiceClient(cc *grpc.ClientConn) StestServiceClient {
	return &stestServiceClient{cc}
}

func (c *stestServiceClient) Stest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/stest.StestService/Stest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StestServiceServer is the server API for StestService service.
type StestServiceServer interface {
	Stest(context.Context, *Empty) (*Empty, error)
}

func RegisterStestServiceServer(s *grpc.Server, srv StestServiceServer) {
	s.RegisterService(&_StestService_serviceDesc, srv)
}

func _StestService_Stest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StestServiceServer).Stest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stest.StestService/Stest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StestServiceServer).Stest(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _StestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stest.StestService",
	HandlerType: (*StestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stest",
			Handler:    _StestService_Stest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stest.proto",
}
